### PR TITLE
Add support for dateRangeInput and airDatePickerInput

### PR DESCRIPTION
**Pull request by pcogis**
I have added the support for dateRangeInputs as well as the airDatePickerInputs (from the shinyWidgets package). 
For the regular dateRange,  there are two dates but I show the icon only on one of the two as two icons seemed excessive. 
The airDatePickerInput includes both the single and multiple date selection.

### CODE REVIEW

**Comment by pcogis** [comment]
I realise there is already a function to add feedback to a pickerInput that works with the airPicker. However, this results in putting the icon in an awkward place. Don't know if it would be good to reuse the existing function and it would be up to the user to not use the icon (or to have it not so clean).

**Comment by merlinoa** [comment]
@pcogis thanks so much for this PR.  We will be reviewing it over the next week or so as we get back to making updates to shinyFeedback.  We hope to merge it and also have a new CRAN release of shinyFeedback ready in the next couple of weeks.

**Review by merlinoa — APPROVED** [review]

**Comment by merlinoa** [comment]
Cool this looks good to me!  Thanks very much for opening up the PR and thanks for your patience with my review.  

In my review process I added examples to a Shiny app for testing.  I noticed that when I added a `shinyWidgets::airDateRangeInput()` to a Shiny app that already had a `shiny::dateInput()` or `shiny::dateRangeInput()` then the dropdown for the shiny date inputs does not work.  Do you know if this is expected behavior?

I am going to assume it is expected behavior for now, and go ahead and merge.  Thanks again for the PR!

**Comment by pcogis** [comment]
Thanks for the merge! 
Indeed `shinyWidgets::airDateRangeInput()` prevents `shiny::dateRangeInput()` from working on the same app as it overwrites some of its behaviour. This is mentioned in the documentation of `shinyWidgets::airDateRangeInput()` so should be clear enough for the users.

**Pull request merged**
